### ISSUE TITLE
Error in tranform_json_to_pickle.py while executing csv_clocq.sh

### ISSUE THREAD

**Issue by rajharshiitb** [PhilippChr/CLOCQ#1]
Traceback (most recent call last):
  File "/mnt/infonas/data/harshiitb/MTP/MTP/CLOCQ/clocq/knowledge_base/creation/csv_to_clocq/transform_json_to_pickle.py", line 53, in <module>
    json_to_encoded_pickle("dicts/aliases_dict.json", "dicts/aliases.pickle")
  File "/mnt/infonas/data/harshiitb/MTP/MTP/CLOCQ/clocq/knowledge_base/creation/csv_to_clocq/transform_json_to_pickle.py", line 28, in json_to_encoded_pickle
    with open(json_path, "r") as fp:
**FileNotFoundError: [Errno 2] No such file or directory: 'dicts/aliases_dict.json'**

From where I can get aliases_dict.json, labels_dict.json, descriptions_dict.json? I don't see these files in ./dicts directory and these are also not the output of any of the python scripts executed before the transform script. 

Thanks and regards,
Harsh

**Comment by PhilippChr** [comment]
The code in the folder csv_to_clocq takes as input the output of this codebase,
ran on a Wikidata n-triples dump: https://github.com/PhilippChr/wikidata-core-for-QA.

For using CLOCQ, you can download the required data via the initialize.sh script.
If you want to use a different Wikidata/KB-dump, you can run take a look at the repo above.

Please let me know if you face further issues.

Regards,
Philipp

**Comment by rajharshiitb** [comment]
The output for https://github.com/PhilippChr/wikidata-core-for-QA is wikidata_clean.csv right? I already have that and was able to run 4 out of 5 scripts but the last script needed three more files: **aliases_dict.json, labels_dict.json, descriptions_dict.json**. Where can I find them? Are they from "initialize.sh script"?

Thanks and regards,
Harsh

**Comment by PhilippChr** [comment]
Oh I see.
So the output is wikidata_clean.csv, but also the dictionaries that are missing for you:
https://github.com/PhilippChr/wikidata-core-for-QA/blob/0af1ac19097fe102da4bde44b6ab9249556d1640/filter_wikidata.py#L367-L384

Regards,
Philipp

**Comment by rajharshiitb** [comment]
Oh got it. It seems I need to run the code for those missing files. By any chance do you still have those files? It'll be really life saver for me -:).

Thanks and Regards,
Harsh

**Comment by PhilippChr** [comment]
Which Wikidata dump did you use (i.e. the timestamp)?
The labels, descriptions, and aliases might change; and also new KB items might be added
which are not present in my dictionaries (this might lead to errors when loading the KB-index; you might be able to catch such cases though).

Regards,
Philipp

**Comment by rajharshiitb** [comment]
Currently I am using Wikidata dump from April 2020, the same from the repo.

Thanks and Regards,
Harsh

**Comment by PhilippChr** [comment]
In that case you can download the (already processed) files using initialize.sh,
or by using this link: http://qa.mpi-inf.mpg.de/clocq/clocq_data.zip.

The files are already transformed to pickle, as expected by CLOCQ.
So there is no need to run the script transform_json_to_pickle.

Regards,
Philipp

**Comment by rajharshiitb** [comment]
Got it. 
Thanks and Regards,
Harsh

**Comment by PhilippChr** [comment]
Alright, great!

Regards,
Philipp
