### ISSUE TITLE
CLOCQ EL API down?

### ISSUE THREAD

**Issue by kmdn** [PhilippChr/CLOCQ#5]
Hey there!

I am working on researching a variety of entity linking approaches, attempting to generate result explanations and ran across CLOCQ - it looks like very useful and interesting project!

I found [https://clocq.mpi-inf.mpg.de/](this) site and wanted to test the EL aspect of the API, but the service seems unavailable.
Will it be coming back up or would you advise rather going for the code?

While I am at it: I am planning on running it on-site along a variety of other services - are you planning on dockerizing CLOCQ? If so, I'd love to include it!

Best regards & continued success!
kmdn

**Comment by PhilippChr** [comment]
Hi,

First of all, thanks a lot for your interest in our work and the nice words!

The EL service was just restarted, thanks for the note.
We will add a regular test to check for its availability.

There are currently no plans to dockerize CLOCQ though.
CLOCQ uses the full Wikidata KB internally, which comes
with quite some disk space and memory requirements.

For the EL service, we provide a module that could be 
run locally, but still makes use of the CLOCQ API:
https://github.com/PhilippChr/CLOCQ-pruning-module/
This essentially wraps around the CLOCQ service/API.

All the best for your research!
Explainability is indeed an interesting topic,
for many IR/NLP related tasks.

Regards,
Philipp
