### ISSUE TITLE
Question about load data to virtuoso

### ISSUE THREAD

**Issue by cdhx** [PhilippChr/CLOCQ#7]
Hi,

I'm sorry to bother you, I have some questions that may not be directly related to this project, but I thought you could help me.

I am trying to import the wikidata dataset into virtuoso, the total ttl file is about 800G, it worked fine in the beginning and loaded about 80G in the first day.

Now I've been loading for about a week and it's getting slower and slower and almost stopped today.

I also tried splitting the TTL into some smaller TTLs (I split it into 300 files), but the virtuoso.db file has not changed at all in the past day and is now 280G in size

Can you give some advice on importing large files, I thought at first that the whole 800G file was too big so it would get stuck at a later stage, but now it doesn't seem to be the case, even if I split the files and import them one by one, it still gets stuck when the database file gets bigger

Any help would be appreciated!

**Comment by PhilippChr** [comment]
Hi,

I am sorry, but unfortunately I can not help you with this problem.
Actually, we faced similar problems with different existing solutions. This was also a reason why we implemented our own KB index from scratch.

Regards,
Philipp

**Comment by cdhx** [comment]
Ok, thanks for your reply anyway！
