### ISSUE TITLE
QA system

### ISSUE THREAD

**Issue by cdhx** [PhilippChr/CLOCQ#8]
Thank you for publishing this tool. It has been really helpful to me!

I am also interested in the QA system mentioned in your paper, "Beyond NED: Fast and Effective Search Space Reduction for Complex Question Answering over Knowledge Bases," especially for LC-QuAD 2.0.

I was wondering if this QA system is open-sourced? If it is, could you please provide me with a link or any relevant information on how to access it?

Thank you again for your contributions to the community. I am looking forward to your reply.

**Comment by PhilippChr** [comment]
Hi,

We are happy that you find our work useful!

The QA system used in this work is GraftNet, for which the code is publicly available at https://github.com/haitian-sun/GraftNet. The work was published at EMNLP 2018 (https://arxiv.org/abs/1809.00782).

We also have a recent QA system from our group, that you might want to check out at https://explaignn.mpi-inf.mpg.de. The work is accepted at SIGIR 2023, and the code and pre-trained models are publicly available here: https://github.com/PhilippChr/EXPLAIGNN.

Regards,
Philipp

**Comment by cdhx** [comment]
Thank you for your kind response.

I have another question regarding the migration of graftnet to LC2. Does the migration solely involve changing entity linking from Freebase to Wikidata? 

Additionally, if I intend to implement a baseline on the Wikidata dataset, e.g. LC2, would you kindly provide any recommended baselines?

Once again, I truly appreciate your patience and assistance.

**Comment by PhilippChr** [comment]
GraftNet requires a set of KB-facts as input.
In our experiments, we gave it either KB-facts as provided by the CLOCQ search space reduction functionality, or KB-facts retrieved for disambiguated entities (via ELQ, TagME,...).
So having an entity linker + a method to retrieve KB-facts for linked entities (e.g. CLOCQ) would be sufficient.

For complex QA, you could e.g. compare with UNIQORN (https://uniqorn.mpi-inf.mpg.de) in KB-only setting, that also has results readily available on LC-QuAD 2.0.
Again, EXPLAIGNN in KB-only setting would also be an option.

Finally, I would also like to point to our latest benchmark release, CompMix (https://qa.mpi-inf.mpg.de/compmix/), that has complex questions with answers grounded in Wikidata. A write-up with additional details will follow soon. We would also provide results of EXPLAIGNN. Questions may often require heterogeneous sources to be answered, but comparison in KB-only setting would also be possible. In case you are interested, let me know, and I could share results of EXPLAIGNN in KB-only setting on this dataset.

**Comment by rroy-fiis** [comment]
Hello,

Connecting you with Soumajit and Jesujoba, who can help you with
intermediate outputs and results of UNIQORN on LC-QuAD 2.0, so that you can
more easily compare your method with UNIQORN.

Regards,
Rishi.

**Comment by cdhx** [comment]
Thank you for your patience!

I will consider using UNIQORN as a baseline and then contact Soumajit and Jesujoba if needed.

Thanks again for your help!
